"""
Query-optimization exercise for the GNSS Log Analyzer.

WHAT THIS DOES
---------------
1. Seeds a realistic volume of rows (default 500,000) directly in Postgres
   via generate_series(), so it's fast and doesn't round-trip through
   pandas/psycopg2 row-by-row.
2. Runs a representative filter query ("recent low-quality readings for one
   time window") and captures real `EXPLAIN (ANALYZE, BUFFERS)` output.
3. Creates a targeted index.
4. Re-runs the same query and captures EXPLAIN ANALYZE again.
5. Writes both plans, plus the headline numbers (planning/execution time,
   whether the planner switched from Seq Scan to Index Scan), into
   docs/query_optimization_results.md.

HONESTY NOTE
------------
This script produces REAL numbers -- but only when run against a live
Postgres/TimescaleDB instance. I don't have network access to install or run
Postgres in this sandbox, so I have not executed this script myself and the
committed docs/query_optimization_results.md is a placeholder, not fabricated
output. Run it yourself against the project's docker-compose Postgres:

    docker-compose up -d db
    docker-compose exec -T db psql -U admin -d gnss_logs -c "SELECT 1;"  # sanity check
    python -m scripts.query_optimization

It will overwrite docs/query_optimization_results.md with real EXPLAIN
ANALYZE output from your machine.
"""

import os
import time

import psycopg2

from backend.config import DB_URL

SEED_ROWS = 500_000
TABLE = "gnss_query_bench"
OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs",
    "query_optimization_results.md",
)

# Representative query: dashboards filtering "recent, low-quality" readings
# for a single device-less time window -- a pattern that shows up in both
# the error-intelligence panel and any future device-scoped report.
BENCH_QUERY = f"""
    SELECT count(*), avg(snr)
    FROM {TABLE}
    WHERE time >= now() - interval '2 days'
      AND time <  now() - interval '1 day'
      AND snr < 20;
"""


def _explain(cur, query):
    cur.execute(f"EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT) {query}")
    return "\n".join(row[0] for row in cur.fetchall())


def main():
    conn = psycopg2.connect(DB_URL)
    conn.autocommit = False
    cur = conn.cursor()

    print(f"Seeding {SEED_ROWS:,} rows into {TABLE} ...")
    cur.execute(f"DROP TABLE IF EXISTS {TABLE};")
    cur.execute(
        f"""
        CREATE TABLE {TABLE} (
            id               BIGSERIAL PRIMARY KEY,
            time             TIMESTAMPTZ NOT NULL,
            lat              DOUBLE PRECISION,
            lon              DOUBLE PRECISION,
            alt              DOUBLE PRECISION,
            satellite_count  INT,
            snr              DOUBLE PRECISION
        );
        """
    )
    cur.execute(
        f"""
        INSERT INTO {TABLE} (time, lat, lon, alt, satellite_count, snr)
        SELECT
            now() - (random() * interval '30 days'),
            23.0 + random(),
            89.0 + random(),
            10 + random() * 40,
            (random() * 12)::int,
            5 + random() * 40
        FROM generate_series(1, {SEED_ROWS});
        """
    )
    conn.commit()
    print("Seed complete.")

    print("Running EXPLAIN ANALYZE BEFORE index...")
    plan_before = _explain(cur, BENCH_QUERY)
    conn.commit()

    print("Creating index on (time, snr)...")
    t0 = time.time()
    cur.execute(f"CREATE INDEX idx_{TABLE}_time_snr ON {TABLE} (time, snr);")
    conn.commit()
    index_build_seconds = time.time() - t0

    cur.execute(f"ANALYZE {TABLE};")
    conn.commit()

    print("Running EXPLAIN ANALYZE AFTER index...")
    plan_after = _explain(cur, BENCH_QUERY)
    conn.commit()

    cur.close()
    conn.close()

    report = f"""# Query Optimization Results

Generated by `scripts/query_optimization.py` against a live Postgres/TimescaleDB
instance. Table: `{TABLE}`, seeded with {SEED_ROWS:,} rows.

## Benchmark query

```sql
{BENCH_QUERY.strip()}
```

## BEFORE index

```
{plan_before}
```

## Index created

```sql
CREATE INDEX idx_{TABLE}_time_snr ON {TABLE} (time, snr);
```

Index build time: {index_build_seconds:.2f}s

## AFTER index

```
{plan_after}
```

## Takeaway

Compare the `Seq Scan` vs `Index Scan` (or `Bitmap Heap Scan`) node and the
`Execution Time` line in each plan above. On a table this size and a filter
this selective (a 1-day window plus `snr < 20`), the composite index on
`(time, snr)` should let the planner satisfy both predicates directly from
the index instead of scanning the full table.
"""

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(report)

    print(f"Wrote results to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
